version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ../.env

  frontend:
   image: dzhuravlevdev/foodgram-frontend
   volumes:
     - ../frontend/:/app/result_build/
   depends_on:
      - db

  web:
    image: dzhuravlevdev/foodgram-backend
    expose:
      - 8000
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - frontend
    env_file:
      - ../.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - web

volumes:
  static:
  media:
  db:
  redoc:
