# Generated by Django 3.2.6 on 2024-02-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240216_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmountRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=150)),
            ],
        ),
    ]
