# Generated by Django 3.2.6 on 2024-02-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredientamountrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecipeIngredients', to='recipes.ingredientamountrecipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientamountrecipe',
            name='amount',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
