# Generated by Django 3.2.6 on 2024-02-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240217_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('e26e24', 'оранжевый'), ('4ab54f', 'зеленый'), ('8574d4', 'фиолетовый'), ('000000', 'черный')], default='000000', max_length=7, unique=True),
        ),
    ]
