# Generated by Django 3.2.6 on 2024-03-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20240311_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.CharField(default=1, help_text='Добавьте количество ингредиента', max_length=150, verbose_name='Количество ингредиента'),
        ),
    ]
