# Generated by Django 3.2.6 on 2024-03-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientAmountRecipe',
        ),
    ]
