# Generated by Django 3.2.6 on 2024-03-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240213_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setpassword',
            name='user',
        ),
        migrations.DeleteModel(
            name='Me',
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.DeleteModel(
            name='SetPassword',
        ),
    ]
